env:
  global:
    - CONAN_USERNAME: 'nshutchinson'
    - CONAN_LOGIN_USERNAME: 'nshutchinson'
    - CONAN_CHANNEL: 'testing'
    - CONAN_UPLOAD: 'https://api.bintray.com/conan/nshutchinson/conan'
    - CONAN_ARCHS: 'x86_64'
    - CONAN_REVISIONS_ENABLED: '1'

linux: &linux
  os: linux
  dist: xenial
  language: python
  python: '3.7'
  services:
    - docker

osx: &osx
  os: osx
  language: generic

matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5

    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 _XCONAN_CPPSTD=default,17

    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 _XCONAN_CPPSTD=default,17

    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 _XCONAN_CPPSTD=default,17

    - <<: *linux
      env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50 _XCONAN_CPPSTD=default,17

    - <<: *linux
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60 _XCONAN_CPPSTD=default,17

    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7 _XCONAN_CPPSTD=default,17

    - <<: *linux
      env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8 _XCONAN_CPPSTD=default,17

    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 _XCONAN_CPPSTD=default,17 _XCONAN_MACOS_VERSIONS=default,10.9

    - <<: *osx
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 _XCONAN_CPPSTD=default,17 _XCONAN_MACOS_VERSIONS=default,10.9

    - <<: *osx
      osx_image: xcode9.3
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 _XCONAN_CPPSTD=default,17 _XCONAN_MACOS_VERSIONS=default,10.9

    - <<: *osx
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 _XCONAN_CPPSTD=default,17 _XCONAN_MACOS_VERSIONS=default,10.9

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
