build: false

environment:
  CONAN_USERNAME: 'nshutchinson'
  CONAN_LOGIN_USERNAME: 'nshutchinson'
  CONAN_CHANNEL: 'testing'
  CONAN_UPLOAD: 'https://api.bintray.com/conan/nshutchinson/conan'
  CONAN_ARCHS: 'x86_64'

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_VISUAL_RUNTIMES: MD,MDd
      ABSEIL_CXX_STD: default,17

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_VISUAL_RUNTIMES: MD,MDd
      ABSEIL_CXX_STD: default,17

install:
  - py -3.7 -m venv .venv
  - .venv\\Scripts\\activate.bat
  - pip install -r requirements.txt
  - conan user

test_script:
  - .venv\\Scripts\\activate.bat
  - python build.py
